# Dependencies
markdown:         redcarpet
highlighter:      pygments
redcarpet:
  extensions        : ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# Permalinks
permalink:        pretty

# Setup
title:            隨手筆記
tagline:          'A Jekyll theme'
description:      'This is my learning note.'
#url:              http://hyde.getpoole.com
baseurl:          '/myblog/'

#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
#version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
